#!/bin/sh
# Generates specs/design/sections/appendix-environment.tex from the machine this
# is run on. Run this on the machine where the test suites were actually run,
# right before a release, and commit the result: do not hand-edit it, and do
# not run it speculatively on a machine that did not run the tests.
#
# usage: specs/tools/tested-environment.sh > specs/design/sections/appendix-environment.tex

set -eu
cd "$(dirname "$0")/../.."   # repo root
WEB=web
ROOT_TEX='specs/design/sections/appendix-environment.tex'

esc() { printf '%s' "$1" | sed 's/[&%$#_{}]/\\&/g; s/\\\\&/\\&/g'; }
# sed above is approximate; do the substitutions in the right order instead:
esc() {
  printf '%s' "$1" | sed -e 's/\\/\\textbackslash{}/g' -e 's/[&%$#_{}]/\\&/g' -e 's/\^/\\^{}/g' -e 's/~/\\~{}/g'
}

GEN_DATE=$(date -u '+%Y-%m-%d %H:%M UTC')
HW_MODEL=$(system_profiler SPHardwareDataType 2>/dev/null | awk -F': ' '/Model Name/{print $2; exit}')
HW_CHIP=$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo unknown)
HW_CORES=$(sysctl -n hw.ncpu 2>/dev/null || echo unknown)
HW_MEM=$(( $(sysctl -n hw.memsize 2>/dev/null || echo 0) / 1073741824 ))
OS_NAME=$(sw_vers -productName)
OS_VER=$(sw_vers -productVersion)
OS_BUILD=$(sw_vers -buildVersion)
ARCH=$(uname -m)
SAFARI_VER=$(defaults read /Applications/Safari.app/Contents/Info CFBundleShortVersionString 2>/dev/null || echo "not installed")
SAFARIDRIVER=$("/usr/bin/safaridriver" --version 2>&1 || echo "not found")
CHROME_VER=$("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --version 2>/dev/null || echo "not installed")
GO_VER=$(go version)
GO_CGO=$(go env CGO_ENABLED)
GO_OS=$(go env GOOS)
GO_ARCH=$(go env GOARCH)
GO_MODS=$(go list -m all 2>/dev/null | tail -n +2)
NODE_VER=$(node -v)
NPM_VER=$(npm -v)
# "name<TAB>version" per direct dependency, from npm's JSON (its tree text
# changes between npm releases, and scoped names contain an @ of their own).
NPM_PKGS=$(cd "$WEB" && npm ls --depth=0 --json 2>/dev/null | node -e '
  const d = JSON.parse(require("fs").readFileSync(0, "utf8")).dependencies || {};
  for (const n of Object.keys(d).sort()) console.log(n + "\t" + d[n].version);')
PDFLATEX_VER=$(pdflatex --version 2>&1 | head -1)
LATEXMK_VER=$(latexmk -v 2>&1 | head -2 | tail -1)
MAKE_VER=$(make -v 2>&1 | head -1)
GIT_VER=$(git --version)
CLANG_VER=$(clang --version 2>&1 | head -1)
MANDOC_NOTE="bundled with macOS $OS_VER as /usr/bin/mandoc (BSD mandoc; the tool exposes no version flag)"

{
cat <<TEX
% Generated by specs/tools/tested-environment.sh on $(esc "$GEN_DATE").
% Do not hand-edit; rerun the script on the machine that ran the tests.
\section{Tested Environment}
\label{sec:environment}

Every result in this document, and every test referenced by it, was produced on the
single machine described below.  Nothing has been run on any other machine, on any
other operating system, or on the browsers this lists as not installed.
Section~\ref{sec:untested} states plainly what that leaves unchecked.

\subsection{Hardware}

\begin{center}
\begin{tabular}{@{}ll@{}}
\toprule
Model & $(esc "$HW_MODEL") \\\\
Chip & $(esc "$HW_CHIP") \\\\
Cores & $(esc "$HW_CORES") \\\\
Memory & ${HW_MEM}~GB \\\\
Architecture & \code{$(esc "$ARCH")} \\\\
\bottomrule
\end{tabular}
\end{center}

\subsection{Operating system and browsers}

\begin{center}
\begin{tabular}{@{}>{\raggedright\arraybackslash}p{0.30\linewidth}>{\raggedright\arraybackslash}p{0.62\linewidth}@{}}
\toprule
$(esc "$OS_NAME") & $(esc "$OS_VER") (build $(esc "$OS_BUILD")) \\\\
Safari & $(esc "$SAFARI_VER") \\\\
\code{safaridriver} & $(esc "$SAFARIDRIVER") \\\\
Google Chrome & $(esc "$CHROME_VER") \\\\
Firefox & not installed; not tested (\fq{DST-4} note; Section~\ref{sec:untested}) \\\\
\bottomrule
\end{tabular}
\end{center}

\subsection{Go toolchain and modules}

\begin{center}
\begin{tabular}{@{}>{\raggedright\arraybackslash}p{0.30\linewidth}>{\raggedright\arraybackslash}p{0.62\linewidth}@{}}
\toprule
Toolchain & \code{$(esc "$GO_VER")} \\\\
\code{GOOS}/\code{GOARCH} & \code{$(esc "$GO_OS")}/\code{$(esc "$GO_ARCH")} \\\\
\code{CGO\_ENABLED} & $(esc "$GO_CGO") (the program uses no cgo; \code{clang} is listed below only because the toolchain can call it) \\\\
\bottomrule
\end{tabular}
\end{center}

Resolved module versions (\code{go list -m all}), exactly as recorded in \code{go.sum}:

\begin{center}
\begin{tabular}{@{}ll@{}}
\toprule
Module & Version \\\\
\midrule
TEX
while IFS=' ' read -r mod ver rest; do
  [ -n "$mod" ] || continue
  printf '\\code{%s} & \\code{%s} \\\\\n' "$(esc "$mod")" "$(esc "$ver")"
done <<EOF
$GO_MODS
EOF
cat <<TEX
\bottomrule
\end{tabular}
\end{center}

\subsection{Front end: Node and npm packages}

\begin{center}
\begin{tabular}{@{}ll@{}}
\toprule
Node.js & \code{$(esc "$NODE_VER")} \\\\
npm & \code{$(esc "$NPM_VER")} \\\\
\bottomrule
\end{tabular}
\end{center}

Installed package versions in \code{web/} (\code{npm ls --depth=0}), which match the
versions pinned in \code{web/package-lock.json}:

\begin{center}
\begin{tabular}{@{}ll@{}}
\toprule
Package & Version \\\\
\midrule
TEX
TAB=$(printf '\t')
printf '%s\n' "$NPM_PKGS" | while IFS=$TAB read -r pkg ver; do
  [ -n "$pkg" ] || continue
  printf '\\code{%s} & \\code{%s} \\\\\n' "$(esc "$pkg")" "$(esc "$ver")"
done
cat <<TEX
\bottomrule
\end{tabular}
\end{center}

\subsection{Build and documentation tools}

\begin{center}
\begin{tabular}{@{}>{\raggedright\arraybackslash}p{0.30\linewidth}>{\raggedright\arraybackslash}p{0.62\linewidth}@{}}
\toprule
\code{make} & $(esc "$MAKE_VER") \\\\
\code{git} & $(esc "$GIT_VER") \\\\
\code{clang} (Xcode Command Line Tools) & $(esc "$CLANG_VER") \\\\
\code{mandoc} & $(esc "$MANDOC_NOTE") \\\\
\LaTeX{} & $(esc "$PDFLATEX_VER") \\\\
\code{latexmk} & $(esc "$LATEXMK_VER") \\\\
\bottomrule
\end{tabular}
\end{center}

The \LaTeX{} packages loaded by the shared preamble (\code{specs/common/preamble.tex})
are: \code{fontenc}, \code{inputenc}, \code{lmodern}, \code{geometry},
\code{microtype}, \code{parskip}, \code{amsmath}, \code{amssymb}, \code{amsthm},
\code{mathtools}, \code{booktabs}, \code{longtable}, \code{array}, \code{enumitem},
\code{needspace}, \code{xcolor}, \code{listings}, \code{fancyhdr}, \code{hyperref},
\code{bookmark}, \code{xurl} and \code{tikz}, all from the TeX Live distribution
named above.

\subsection{Regenerating this section}

This section is generated, not written by hand.  On the machine that ran the tests:

\begin{lstlisting}[language=bash]
specs/tools/tested-environment.sh > specs/design/sections/appendix-environment.tex
make -C specs design
\end{lstlisting}
TEX
} > "$ROOT_TEX"
echo "wrote $ROOT_TEX" >&2
